- name: Setup TFLint
  # You may pin to the exact commit or the version.
  # uses: terraform-linters/setup-tflint@7cf6558386ea02736c0a5edd3031f39c2dfeb206
  uses: terraform-linters/setup-tflint@v1.1.0
